
#!/bin/bash

# Correct patterns
pattern1='MUSICOS, ARTISTAS, EMPRESARIOS Y PRUD ESPECT'
pattern2='DEPORTISTAS, ENTRENADORES, TECNICOS DEPORT'
pattern3='HISTORIADOR, Y PROFESEN CIENCIAS POLITICAS'
pattern4='ESCRITORES, PERIODISTAS Y TRABAJADORES SIMIL'
pattern5='SOCIOLOGO, ANTROPOLOGOS Y ESPECIALISTA SIMIL'
pattern6='BIBLIOTECARIOS, ARCHIVEROS Y ENCARGA DE MUSEO'
pattern7='ESCULTORES, PINTORES, FOTOGRAFOS Y ART SIMI'
pattern8='FILOSOFOS, TRADUCTORES E INTERPRETES'


sed -i "s/$pattern1/MUSICOS ARTISTAS EMPRESARIOS Y PRUD ESPECT/g" dt2020_base_evaluar.csv 
sed -i "s/$pattern2/DEPORTISTAS ENTRENADORES TECNICOS DEPORT/g" dt2020_base_evaluar.csv
sed -i "s/$pattern3/HISTORIADOR Y PROFESEN CIENCIAS POLITICAS/g" dt2020_base_evaluar.csv
sed -i "s/$pattern4/ESCRITORES PERIODISTAS Y TRABAJADORES SIMIL/g" dt2020_base_evaluar.csv
sed -i "s/$pattern5/SOCIOLOGO ANTROPOLOGOS Y ESPECIALISTA SIMIL/g" dt2020_base_evaluar.csv 
sed -i "s/$pattern6/BIBLIOTECARIOS ARCHIVEROS Y ENCARGA DE MUSEO/g" dt2020_base_evaluar.csv
sed -i "s/$pattern7/ESCULTORES PINTORES FOTOGRAFOS Y ART SIMI/g" dt2020_base_evaluar.csv
sed -i "s/$pattern8/FILOSOFOS TRADUCTORES E INTERPRETES/g" dt2020_base_evaluar.csv

echo "Data cleaned"
